### ISSUE TITLE
Release TODO

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/stevecinema-issues#2]
- [x] [Create installer](https://github.com/Ruinscraft/stevecinema-issues/issues/1)
- [x] Create economy plugin
- [ ] [Implement slot machines in ruinscraft-gambling](https://github.com/Ruinscraft/ruinscraft-gambling) (@masondaniels ?)
- [x] Finish chat gambling plugin (/roll, /coinflip)
- [x] [Implement chat channels for theater rooms in ruinscraft-chat](https://github.com/Ruinscraft/ruinscraft-chat/blob/rewrite4/src/main/java/com/ruinscraft/chat/channel/cinema/TheaterChatChannel.java)
- [ ] Create chairs plugin - allows setting predefined spots to sit (invis armor stands in the world you can mount to)
- [ ] Create plugin for server item shop (for weapons, cosmetics, etc). Also handles pvp mechanics and cosmetic mechanics
- [ ] Add a way to report a video
- [x] Add voteskip
- [ ] Add a way to save playlists (for sponsors+)
- [x] Fix JCEF linux support (a pain)
- [x] Add ownership concept for theater rooms, owners get certain privileges
- [x] Finish web pages for server
- [x] Write server rules
- [x] Figure out how to support cinemadisplays-mod on Java 16
- [x] Ensure players cannot hear pvp sounds etc from outside a theater room (if they're in one)
- [x] Add volume control for screens
- [x] Create voice chat mod
- [ ] Clean up and rebrand the voice chat mod
- [x] Add compatibility and version message to all mods to ensure a compatible version is installed on the client
- [x] Public theaters should not forceskip video if they have no viewers
- [ ] Add tooltip for video titles in history Screen (cinemadisplays)
- [ ] Add video length to entry in history Screen (cinemadisplays)
- [ ] Add seek/pause for videos (cinemadisplays)

not finished
